# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import copy
import dataclasses
import pathlib
from typing import Final

from icon4py.model.common.grid import icon as icon_grid
from icon4py.model.standalone_driver import config as driver_config
from icon4py.model.testing import config


SERIALIZED_DATA_DIR: Final = "ser_icondata"
SERIALIZED_DATA_SUBDIR: Final = "ser_data"
GRID_DATA_DIR: Final = "grids"
EXPERIMENT_DATA_DIR: Final = "experiments"
MUPHYS_DATA_DIR: Final = "muphys"
TESTDATA_ROOT_URL: Final = "https://rgw.cscs.ch/c2sm:testdata"


def serialized_data_path() -> pathlib.Path:
    return config.TEST_DATA_PATH.joinpath(SERIALIZED_DATA_DIR)


def grids_path() -> pathlib.Path:
    return config.TEST_DATA_PATH.joinpath(GRID_DATA_DIR)


@dataclasses.dataclass
class GridDescription:
    name: str
    description: str
    params: icon_grid.GridParams
    limited_area: bool = False


class Grids:
    R01B01_GLOBAL: Final = GridDescription(
        name="R01B01",
        description="R01B01",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=1, level=1),
            ),
        ),
    )
    R02B04_GLOBAL: Final = GridDescription(
        name="icon_grid_0013_R02B04_R",
        description="R02B04, small global grid, default grid used in ICON testing, origin of this file is unclear (source = icon-dev)",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=2, level=4),
            ),
        ),
    )
    R02B06_GLOBAL: Final = GridDescription(
        name="icon_grid_0021_R02B06_G",
        description="R02B06, generated by MPI-M GridGenerator",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=2, level=6),
            ),
        ),
    )
    R02B07_GLOBAL: Final = GridDescription(
        name="icon_grid_0023_R02B07_G",
        description="R02B07, large global grid, generated by MPI-M GridGenerator",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=2, level=7),
            ),
        ),
    )
    R19_B07_MCH_LOCAL: Final = GridDescription(
        name="icon_grid_0002_R19B07_mch",
        description="Grid used in the full icon-ch2 (2km resolution) operational setup of MeteoSwiss, generated by icontools (DWD)",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=19, level=7),
            ),
        ),
        limited_area=True,
    )
    MCH_OPR_R04B07_DOMAIN01: Final = GridDescription(
        name="mch_opr_R04B07_DOM01",
        description="Grid used in the icon-ch2_small experiment (generated by IconTools (DWD) (used by MeteoSwiss for verification of icon-ch2 setup) )",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=4, level=7),
            ),
        ),
        limited_area=True,
    )
    MCH_OPR_R19B08_DOMAIN01: Final = GridDescription(
        name="mch_opr_R19B08_DOM01",
        description="Grid used in some older MCH experiment, suitable for running single GPU benchmarks",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=19, level=8),
            ),
        ),
        limited_area=True,
    )
    MCH_CH_R04B09_DSL: Final = GridDescription(
        name="mch_ch_R04B09_DOM01",
        description="grid used in the mch_ch_r04b09_dsl experiment used for verification of ICON-exclaim DSL port, generated by IconTools (DWD)",
        params=icon_grid.GridParams(
            icon_grid.IcosahedronParams(
                subdivision=icon_grid.GridSubdivision(root=4, level=9),
            ),
        ),
        limited_area=True,
    )
    TORUS_100X116_1000M: Final = GridDescription(
        name="torus_100000mx100000m_res1000m",
        description="Torus grid with a domain (100_000 m x 100_000 m) and an equivalent resolution of 1000 m, generated by MPI-M GridGenerator",
        params=icon_grid.GridParams(
            icon_grid.TorusParams(
                domain_length=100000.0,
                domain_height=100458.94683899487,
            ),
        ),
    )
    TORUS_50000x5000: Final = GridDescription(
        name="torus_50000mx5000m_res500m",
        description="Torus grid with a domain (50_000 m x 5000 m) and an equivalent resolution of 500 m, generated by MPI-M GridGenerator",
        params=icon_grid.GridParams(
            icon_grid.TorusParams(
                domain_length=50000.0,
                domain_height=5248.638810814779,
            ),
        ),
    )
    TORUS_1000X1000_250M: Final = GridDescription(
        name="torus_1000mx1000m_res250m",
        description="Torus grid with a domain (1000 m x 1000 m) and an equivalent resolution of 250 m, generated by MPI-M GridGenerator",
        params=icon_grid.GridParams(
            icon_grid.TorusParams(
                domain_length=1000.0,
                domain_height=1154.7005383792514,
            ),
        ),
    )


@dataclasses.dataclass
class ExperimentDescription:
    name: str
    long_name: str
    grid: GridDescription
    version: int = 5


@dataclasses.dataclass
class Experiment:
    description: ExperimentDescription
    _config: driver_config.ExperimentConfig

    def __init__(
        self,
        experiment_description: ExperimentDescription,
        experiment_config: driver_config.ExperimentConfig,
    ) -> None:
        self.description = experiment_description
        self._config = experiment_config

    @property
    def name(self) -> str:
        return self.description.name

    @property
    def grid(self) -> GridDescription:
        return self.description.grid

    @property
    def config(self) -> driver_config.ExperimentConfig:
        # Return a deep copy so that tests cannot mutate the shared cached config.
        return copy.deepcopy(self._config)


class Experiments:
    EXCLAIM_APE: Final = ExperimentDescription(
        name="exclaim_ape_R02B04",
        long_name="EXCLAIM Aquaplanet experiment",
        grid=Grids.R02B04_GLOBAL,
    )
    EXCLAIM_APE_AES: Final = ExperimentDescription(
        name="exclaim_ape_aesPhys",
        long_name="EXCLAIM Aquaplanet experiment. JW IC and AES physics",
        grid=Grids.R02B04_GLOBAL,
    )
    MCH_CH_R04B09: Final = ExperimentDescription(
        name="exclaim_ch_r04b09_dsl",
        long_name="Regional setup used by EXCLAIM to validate the icon-exclaim.",
        grid=Grids.MCH_CH_R04B09_DSL,
    )
    JW: Final = ExperimentDescription(
        name="exclaim_nh35_tri_jws",
        long_name="Jablonowski Williamson atmospheric test case",
        grid=Grids.R02B04_GLOBAL,
    )
    GAUSS3D: Final = ExperimentDescription(
        name="exclaim_gauss3d",
        long_name="Gauss 3d test case",
        grid=Grids.TORUS_50000x5000,
    )
    WEISMAN_KLEMP_TORUS: Final = ExperimentDescription(
        name="exclaim_nh_weisman_klemp",
        long_name="Weisman-Klemp experiment on Torus Grid",
        grid=Grids.TORUS_50000x5000,
    )
