#ifndef ICON4PY_BINDINGS_H
#define ICON4PY_BINDINGS_H

extern int diffusion_init_wrapper(
    double *theta_ref_mc, int theta_ref_mc_size_0, int theta_ref_mc_size_1,
    double *wgtfac_c, int wgtfac_c_size_0, int wgtfac_c_size_1,
    double *e_bln_c_s, int e_bln_c_s_size_0, int e_bln_c_s_size_1,
    double *geofac_div, int geofac_div_size_0, int geofac_div_size_1,
    double *geofac_grg_x, int geofac_grg_x_size_0, int geofac_grg_x_size_1,
    double *geofac_grg_y, int geofac_grg_y_size_0, int geofac_grg_y_size_1,
    double *geofac_n2s, int geofac_n2s_size_0, int geofac_n2s_size_1,
    double *nudgecoeff_e, int nudgecoeff_e_size_0, double *rbf_vec_coeff_v,
    int rbf_vec_coeff_v_size_0, int rbf_vec_coeff_v_size_1,
    int rbf_vec_coeff_v_size_2, int *zd_cellidx, int zd_cellidx_size_0,
    int zd_cellidx_size_1, int *zd_vertidx, int zd_vertidx_size_0,
    int zd_vertidx_size_1, double *zd_intcoef, int zd_intcoef_size_0,
    int zd_intcoef_size_1, double *zd_diffcoef, int zd_diffcoef_size_0,
    int ndyn_substeps, int diffusion_type, unsigned char hdiff_w,
    unsigned char hdiff_vn, unsigned char hdiff_smag_w, unsigned char zdiffu_t,
    int type_t_diffu, int type_vn_diffu, double hdiff_efdt_ratio,
    double hdiff_w_efdt_ratio, double smagorinski_scaling_factor,
    double smagorinski_scaling_factor2, double smagorinski_scaling_factor3,
    double smagorinski_scaling_factor4, double smagorinski_scaling_height,
    double smagorinski_scaling_height2, double smagorinski_scaling_height3,
    double smagorinski_scaling_height4, unsigned char hdiff_temp,
    double denom_diffu_v, double nudge_max_coeff, int itype_sher, int iforcing,
    double a_hshr, unsigned char loutshs, int backend, unsigned char on_gpu);
extern int diffusion_run_wrapper(
    double *w, int w_size_0, int w_size_1, double *vn, int vn_size_0,
    int vn_size_1, double *exner, int exner_size_0, int exner_size_1,
    double *theta_v, int theta_v_size_0, int theta_v_size_1, double *rho,
    int rho_size_0, int rho_size_1, double *hdef_ic, int hdef_ic_size_0,
    int hdef_ic_size_1, double *div_ic, int div_ic_size_0, int div_ic_size_1,
    double *dwdx, int dwdx_size_0, int dwdx_size_1, double *dwdy,
    int dwdy_size_0, int dwdy_size_1, double dtime, unsigned char linit,
    unsigned char on_gpu);
extern int grid_init_wrapper(
    int *cell_starts, int cell_starts_size_0, int *cell_ends,
    int cell_ends_size_0, int *vertex_starts, int vertex_starts_size_0,
    int *vertex_ends, int vertex_ends_size_0, int *edge_starts,
    int edge_starts_size_0, int *edge_ends, int edge_ends_size_0, int *c2e,
    int c2e_size_0, int c2e_size_1, int *e2c, int e2c_size_0, int e2c_size_1,
    int *c2e2c, int c2e2c_size_0, int c2e2c_size_1, int *e2c2e,
    int e2c2e_size_0, int e2c2e_size_1, int *e2v, int e2v_size_0,
    int e2v_size_1, int *v2e, int v2e_size_0, int v2e_size_1, int *v2c,
    int v2c_size_0, int v2c_size_1, int *e2c2v, int e2c2v_size_0,
    int e2c2v_size_1, int *c2v, int c2v_size_0, int c2v_size_1,
    unsigned char *c_owner_mask, int c_owner_mask_size_0,
    unsigned char *e_owner_mask, int e_owner_mask_size_0,
    unsigned char *v_owner_mask, int v_owner_mask_size_0, int *c_glb_index,
    int c_glb_index_size_0, int *e_glb_index, int e_glb_index_size_0,
    int *v_glb_index, int v_glb_index_size_0, double *tangent_orientation,
    int tangent_orientation_size_0, double *inverse_primal_edge_lengths,
    int inverse_primal_edge_lengths_size_0, double *inv_dual_edge_length,
    int inv_dual_edge_length_size_0, double *inv_vert_vert_length,
    int inv_vert_vert_length_size_0, double *edge_areas, int edge_areas_size_0,
    double *f_e, int f_e_size_0, double *cell_center_lat,
    int cell_center_lat_size_0, double *cell_center_lon,
    int cell_center_lon_size_0, double *cell_areas, int cell_areas_size_0,
    double *primal_normal_vert_x, int primal_normal_vert_x_size_0,
    int primal_normal_vert_x_size_1, double *primal_normal_vert_y,
    int primal_normal_vert_y_size_0, int primal_normal_vert_y_size_1,
    double *dual_normal_vert_x, int dual_normal_vert_x_size_0,
    int dual_normal_vert_x_size_1, double *dual_normal_vert_y,
    int dual_normal_vert_y_size_0, int dual_normal_vert_y_size_1,
    double *primal_normal_cell_x, int primal_normal_cell_x_size_0,
    int primal_normal_cell_x_size_1, double *primal_normal_cell_y,
    int primal_normal_cell_y_size_0, int primal_normal_cell_y_size_1,
    double *dual_normal_cell_x, int dual_normal_cell_x_size_0,
    int dual_normal_cell_x_size_1, double *dual_normal_cell_y,
    int dual_normal_cell_y_size_0, int dual_normal_cell_y_size_1,
    double *edge_center_lat, int edge_center_lat_size_0,
    double *edge_center_lon, int edge_center_lon_size_0,
    double *primal_normal_x, int primal_normal_x_size_0,
    double *primal_normal_y, int primal_normal_y_size_0, double *vct_a,
    int vct_a_size_0, double lowest_layer_thickness, double model_top_height,
    double stretch_factor, double flat_height, double rayleigh_damping_height,
    double mean_cell_area, int comm_id, int num_vertices, int num_cells,
    int num_edges, int vertical_size, unsigned char limited_area, int backend,
    unsigned char on_gpu);
extern int solve_nh_init_wrapper(
    double *c_lin_e, int c_lin_e_size_0, int c_lin_e_size_1, double *c_intp,
    int c_intp_size_0, int c_intp_size_1, double *e_flx_avg,
    int e_flx_avg_size_0, int e_flx_avg_size_1, double *geofac_grdiv,
    int geofac_grdiv_size_0, int geofac_grdiv_size_1, double *geofac_rot,
    int geofac_rot_size_0, int geofac_rot_size_1, double *pos_on_tplane_e_1,
    int pos_on_tplane_e_1_size_0, int pos_on_tplane_e_1_size_1,
    double *pos_on_tplane_e_2, int pos_on_tplane_e_2_size_0,
    int pos_on_tplane_e_2_size_1, double *rbf_vec_coeff_e,
    int rbf_vec_coeff_e_size_0, int rbf_vec_coeff_e_size_1, double *e_bln_c_s,
    int e_bln_c_s_size_0, int e_bln_c_s_size_1, double *rbf_vec_coeff_v,
    int rbf_vec_coeff_v_size_0, int rbf_vec_coeff_v_size_1,
    int rbf_vec_coeff_v_size_2, double *geofac_div, int geofac_div_size_0,
    int geofac_div_size_1, double *geofac_n2s, int geofac_n2s_size_0,
    int geofac_n2s_size_1, double *geofac_grg_x, int geofac_grg_x_size_0,
    int geofac_grg_x_size_1, double *geofac_grg_y, int geofac_grg_y_size_0,
    int geofac_grg_y_size_1, double *nudgecoeff_e, int nudgecoeff_e_size_0,
    unsigned char *mask_prog_halo_c, int mask_prog_halo_c_size_0,
    double *rayleigh_w, int rayleigh_w_size_0, double *exner_exfac,
    int exner_exfac_size_0, int exner_exfac_size_1, double *exner_ref_mc,
    int exner_ref_mc_size_0, int exner_ref_mc_size_1, double *wgtfac_c,
    int wgtfac_c_size_0, int wgtfac_c_size_1, double *wgtfacq_c,
    int wgtfacq_c_size_0, int wgtfacq_c_size_1, double *inv_ddqz_z_full,
    int inv_ddqz_z_full_size_0, int inv_ddqz_z_full_size_1, double *rho_ref_mc,
    int rho_ref_mc_size_0, int rho_ref_mc_size_1, double *theta_ref_mc,
    int theta_ref_mc_size_0, int theta_ref_mc_size_1, double *vwind_expl_wgt,
    int vwind_expl_wgt_size_0, double *d_exner_dz_ref_ic,
    int d_exner_dz_ref_ic_size_0, int d_exner_dz_ref_ic_size_1,
    double *ddqz_z_half, int ddqz_z_half_size_0, int ddqz_z_half_size_1,
    double *theta_ref_ic, int theta_ref_ic_size_0, int theta_ref_ic_size_1,
    double *d2dexdz2_fac1_mc, int d2dexdz2_fac1_mc_size_0,
    int d2dexdz2_fac1_mc_size_1, double *d2dexdz2_fac2_mc,
    int d2dexdz2_fac2_mc_size_0, int d2dexdz2_fac2_mc_size_1,
    double *rho_ref_me, int rho_ref_me_size_0, int rho_ref_me_size_1,
    double *theta_ref_me, int theta_ref_me_size_0, int theta_ref_me_size_1,
    double *ddxn_z_full, int ddxn_z_full_size_0, int ddxn_z_full_size_1,
    double *zdiff_gradp, int zdiff_gradp_size_0, int zdiff_gradp_size_1,
    int zdiff_gradp_size_2, int *vertidx_gradp, int vertidx_gradp_size_0,
    int vertidx_gradp_size_1, int vertidx_gradp_size_2, int *pg_edgeidx,
    int pg_edgeidx_size_0, int *pg_vertidx, int pg_vertidx_size_0,
    double *pg_exdist, int pg_exdist_size_0, double *ddqz_z_full_e,
    int ddqz_z_full_e_size_0, int ddqz_z_full_e_size_1, double *ddxt_z_full,
    int ddxt_z_full_size_0, int ddxt_z_full_size_1, double *wgtfac_e,
    int wgtfac_e_size_0, int wgtfac_e_size_1, double *wgtfacq_e,
    int wgtfacq_e_size_0, int wgtfacq_e_size_1, double *vwind_impl_wgt,
    int vwind_impl_wgt_size_0, double *hmask_dd3d, int hmask_dd3d_size_0,
    double *scalfac_dd3d, int scalfac_dd3d_size_0, double *coeff1_dwdz,
    int coeff1_dwdz_size_0, int coeff1_dwdz_size_1, double *coeff2_dwdz,
    int coeff2_dwdz_size_0, int coeff2_dwdz_size_1, double *coeff_gradekin,
    int coeff_gradekin_size_0, int coeff_gradekin_size_1,
    unsigned char *c_owner_mask, int c_owner_mask_size_0, int itime_scheme,
    int iadv_rhotheta, int igradp_method, int rayleigh_type, int divdamp_order,
    int divdamp_type, unsigned char l_vert_nested, unsigned char ldeepatmo,
    unsigned char iau_init, unsigned char extra_diffu, double rhotheta_offctr,
    double veladv_offctr, double nudge_max_coeff, double divdamp_fac,
    double divdamp_fac2, double divdamp_fac3, double divdamp_fac4,
    double divdamp_z, double divdamp_z2, double divdamp_z3, double divdamp_z4,
    int nflat_gradp, int backend, unsigned char on_gpu);
extern int solve_nh_run_wrapper(
    double *rho_now, int rho_now_size_0, int rho_now_size_1, double *rho_new,
    int rho_new_size_0, int rho_new_size_1, double *exner_now,
    int exner_now_size_0, int exner_now_size_1, double *exner_new,
    int exner_new_size_0, int exner_new_size_1, double *w_now, int w_now_size_0,
    int w_now_size_1, double *w_new, int w_new_size_0, int w_new_size_1,
    double *theta_v_now, int theta_v_now_size_0, int theta_v_now_size_1,
    double *theta_v_new, int theta_v_new_size_0, int theta_v_new_size_1,
    double *vn_now, int vn_now_size_0, int vn_now_size_1, double *vn_new,
    int vn_new_size_0, int vn_new_size_1, double *w_concorr_c,
    int w_concorr_c_size_0, int w_concorr_c_size_1, double *ddt_vn_apc_ntl1,
    int ddt_vn_apc_ntl1_size_0, int ddt_vn_apc_ntl1_size_1,
    double *ddt_vn_apc_ntl2, int ddt_vn_apc_ntl2_size_0,
    int ddt_vn_apc_ntl2_size_1, double *ddt_w_adv_ntl1,
    int ddt_w_adv_ntl1_size_0, int ddt_w_adv_ntl1_size_1,
    double *ddt_w_adv_ntl2, int ddt_w_adv_ntl2_size_0,
    int ddt_w_adv_ntl2_size_1, double *theta_v_ic, int theta_v_ic_size_0,
    int theta_v_ic_size_1, double *rho_ic, int rho_ic_size_0, int rho_ic_size_1,
    double *exner_pr, int exner_pr_size_0, int exner_pr_size_1,
    double *exner_dyn_incr, int exner_dyn_incr_size_0,
    int exner_dyn_incr_size_1, double *ddt_exner_phy, int ddt_exner_phy_size_0,
    int ddt_exner_phy_size_1, double *grf_tend_rho, int grf_tend_rho_size_0,
    int grf_tend_rho_size_1, double *grf_tend_thv, int grf_tend_thv_size_0,
    int grf_tend_thv_size_1, double *grf_tend_w, int grf_tend_w_size_0,
    int grf_tend_w_size_1, double *mass_fl_e, int mass_fl_e_size_0,
    int mass_fl_e_size_1, double *ddt_vn_phy, int ddt_vn_phy_size_0,
    int ddt_vn_phy_size_1, double *grf_tend_vn, int grf_tend_vn_size_0,
    int grf_tend_vn_size_1, double *vn_ie, int vn_ie_size_0, int vn_ie_size_1,
    double *vt, int vt_size_0, int vt_size_1, double *vn_incr,
    int vn_incr_size_0, int vn_incr_size_1, double *rho_incr,
    int rho_incr_size_0, int rho_incr_size_1, double *exner_incr,
    int exner_incr_size_0, int exner_incr_size_1, double *mass_flx_me,
    int mass_flx_me_size_0, int mass_flx_me_size_1, double *mass_flx_ic,
    int mass_flx_ic_size_0, int mass_flx_ic_size_1, double *vol_flx_ic,
    int vol_flx_ic_size_0, int vol_flx_ic_size_1, double *vn_traj,
    int vn_traj_size_0, int vn_traj_size_1, double dtime,
    double *max_vcfl_size1_array, int max_vcfl_size1_array_size_0,
    unsigned char lprep_adv, unsigned char at_initial_timestep,
    double divdamp_fac_o2, int ndyn_substeps_var, int idyn_timestep,
    unsigned char is_iau_active, double iau_wgt_dyn, unsigned char on_gpu);

#endif
