#! /bin/bash

module load daint-gpu

# Use GT4Py
for backend in numpy gtmc gtx86 gtc:dace gtcuda; do
  for nx in 30 50 100 200 500 1000 1500; do
      # Multiple trials
      for i in 1 2 3 4 5; do
         python3 BurgersWENOdriver.py --nx=${nx} --ny=30 --nz=1 --gt4py=True --tmp=True --backend=${backend} --time=True
      done
   done
done

# Use NumPy
for nx in 30 50 100 200 500 1000 1500; do
   for i in 1 2 3 4 5; do  
      python3 BurgersWENOdriver.py --nx=${nx} --ny=30 --nz=1 --gt4py=False --time=True
   done
done

# Use GT4Py(numpy) without temporary variables
for nx in 30 50 100 200 500 1000 1500; do 
   for i in 1 2 3 4 5; do
      python3 BurgersWENOdriver.py --nx=${nx} --ny=30 --nz=1 --gt4py=True --backend=numpy --time=True --tmp=False
   done
done
