"""Per-process consistency: the port must match the Fortran at every stage boundary.

This is the test that per-process coverage should have been all along. One Fortran run
per scenario dumps the column at each of the nine process boundaries at full precision
(``mo_stage_dump.f90``); the port records its own state at the same boundaries
(``Driver.run_timestep(..., stages=...)``); the two are compared stage by stage.

WHY THIS REPLACES THE OLD PER-PROCESS TESTS
-------------------------------------------
The previous unit tests drove each stencil directly with mid-pipeline inputs that had
been pasted in as 9-12 digit literals, captured from instrumented Fortran runs that were
then reverted. Three problems, all fatal to the purpose:

* the values could not be regenerated by anyone, so a change to the Fortran could not be
  followed;
* the transcription itself capped the achievable tolerance, which is why those tests
  asserted at 1e-6 to 1e-9 -- loose enough to accept a genuine 5e-7 coefficient error;
* the inputs were only as correct as the person copying them. The old
  `test_ice_nucleation.py` carried a comment recording that a rebasing pass had already
  introduced a 10x transcription error, caught only because a test happened to fail.

Comparing at boundaries rather than calling stencils directly also tests the *wiring* --
argument order, which clip runs where, which state feeds the next process -- which is
where a port is at least as likely to go wrong as in a formula, and which no
single-stencil test can see.

Whole-column agreement (``integration_tests/test_full_column.py``) can hide a pair of
cancelling errors; a stage-by-stage comparison cannot.
"""

from __future__ import annotations

import gt4py.next as gtx
import pytest

from minimal_mcrph.driver import ColumnState, Driver
from minimal_mcrph.tests.conftest import compare_columns
from minimal_mcrph.tests.fortran_runner import STAGES, run_fortran
from minimal_mcrph.tests.scenarios import SCENARIOS

_NAMES = sorted(SCENARIOS)
_STATE_FIELDS = tuple(
    f.name for f in ColumnState.__dataclass_fields__.values() if f.name != "hhl"
)

# Fields carried through every stage dump. `rho`, `pres` and `w` are inputs the scheme
# never writes, so comparing them would only re-check the CSV round trip.
_STAGE_CHECKED = (
    "tk", "qv", "qc", "qnc", "qr", "qnr", "qi", "qni",
    "qs", "qns", "qg", "qng", "qh", "qnh", "nccn", "ninpot", "ninact",
)  # fmt: skip


@pytest.fixture(scope="module", params=_NAMES)
def stage_pair(request):
    """Run one scenario through both implementations, returning their stage snapshots.

    Module-scoped and parametrised so each scenario costs one Fortran invocation and one
    port run for all nine stage assertions, rather than one per stage.
    """
    name = request.param
    fields, hhl, dt = SCENARIOS[name]

    _, fortran_stages = run_fortran(fields, hhl, dt=dt, want_stages=True)

    state = ColumnState(hhl=hhl, **{n: fields[n].copy() for n in _STATE_FIELDS})
    port_stages = {}
    Driver().run_timestep(state, dt=dt, stages=port_stages)

    return name, port_stages, fortran_stages


@pytest.mark.parametrize("stage", STAGES)
def test_stage_matches_fortran(stage_pair, stage):
    name, port_stages, fortran_stages = stage_pair
    compare_columns(
        f"{name}/{stage}", port_stages[stage], fortran_stages[stage], fields=_STAGE_CHECKED
    )


def test_every_boundary_is_covered(stage_pair):
    """The port must record a snapshot at each boundary the Fortran dumps.

    Guards against the two halves drifting apart: if a stage were added to
    ``mo_stage_dump.f90`` and not to ``Driver.run_timestep``, the parametrised test above
    would simply never see it.
    """
    _, port_stages, fortran_stages = stage_pair
    assert set(port_stages) == set(fortran_stages) == set(STAGES)


@pytest.mark.parametrize("backend", [gtx.gtfn_cpu], ids=["gtfn_cpu"])
def test_stages_match_fortran_compiled(backend):
    """The same check under the compiled backend, on one scenario.

    Compilation dominates the runtime here, so this deliberately covers a single column
    rather than all six: what it is really testing is that the generated code agrees with
    the embedded execution, and a backend discrepancy would not be scenario-specific.
    The constants wiring in particular only fails under gtfn -- a plain module-level
    float referenced inside a field_operator resolves fine under embedded execution and
    fails to compile here, which is why every stencil module keeps its constants in an
    enum.
    """
    name = "deep_cold"
    fields, hhl, dt = SCENARIOS[name]

    _, fortran_stages = run_fortran(fields, hhl, dt=dt, want_stages=True)

    state = ColumnState(hhl=hhl, **{n: fields[n].copy() for n in _STATE_FIELDS})
    port_stages = {}
    Driver(backend=backend).run_timestep(state, dt=dt, stages=port_stages)

    for stage in STAGES:
        compare_columns(
            f"{name}/{stage}/gtfn", port_stages[stage], fortran_stages[stage],
            fields=_STAGE_CHECKED,
        )  # fmt: skip
