"""The Segal & Khain CCN activation lookup table.

Scope note: the *activation* path -- gate logic, table interpolation, the nucleation
formula and the ``n_cn`` depletion -- is covered against the real Fortran by
``test_stage_boundaries.py`` at the ``ccn`` boundary, on both a column where the gate
stays shut (``bundled``, ``w == 0`` throughout) and one where it opens (``updraft``).
Those checks run the whole pipeline, so they are strictly better than driving
``ccn_activation_sk_4d`` with mid-pipeline values pasted from a one-off instrumented run,
which is what this file used to do.

What they do *not* cover is the table itself away from the points the scenarios happen to
land on. ``build_ccn_table`` interpolates a small non-equidistant table onto a 3x5x129x11
equidistant grid once at start-up; a scenario only ever probes the handful of cells its
own (r2, lsigs, ncn, wcb) reach. The corner check below is the part that is genuinely not
redundant.
"""

from __future__ import annotations

import numpy as np
import pytest

from minimal_mcrph import ccn_activation as ccn


@pytest.fixture(scope="module")
def table():
    return ccn.build_ccn_table()


def test_ccn_table_shape_and_axes(table):
    """Grid geometry, which is exact and so can be asserted exactly.

    ``equi_table`` builds an equidistant grid, so each axis must have constant spacing and
    the stored reciprocal spacing must agree with it. This catches an off-by-one or a
    transposed axis immediately, and unlike the value check below it needs no reference
    data at all.
    """
    assert table.ltable.shape == (3, 5, 129, 11)
    for axis, odx in (
        (table.x1, table.odx1),
        (table.x2, table.odx2),
        (table.x3, table.odx3),
        (table.x4, table.odx4),
    ):
        steps = np.diff(axis)
        np.testing.assert_allclose(steps, steps[0], rtol=1e-14)
        np.testing.assert_allclose(odx, 1.0 / steps[0], rtol=1e-14)

    assert np.all(table.ltable >= 0.0), "activated CCN number cannot be negative"
    assert np.all(np.isfinite(table.ltable))


# Spot values dumped from `tab%ltable` inside mo_2mom_mcrph_processes.f90::equi_table
# during a one-off instrumented run. These are the only reference numbers left in the
# suite that cannot be regenerated by running the driver, and they are quoted to 5-9
# significant digits, which is why the tolerance below is 1e-4 rather than 1e-13.
#
# That is a real weakness and it is recorded rather than hidden: it is tolerable only
# because this is a corner check on a smooth interpolation whose behaviour in the regions
# that matter is pinned properly by the `ccn` stage boundary. If the table build is ever
# changed, dump it again from `equi_table` rather than trusting these.
_CORNERS = {
    (0, 0, 0, 0): 0.0,
    (1, 2, 64, 5): 1.8818e9,
    (2, 4, 128, 10): 2.4647e9,
    (0, 0, 9, 1): 1.84425e8,
    (2, 0, 49, 2): 1.94726875e9,
}


@pytest.mark.parametrize("index", sorted(_CORNERS))
def test_ccn_table_corner_values(table, index):
    expected = _CORNERS[index]
    got = table.ltable[index]
    if expected == 0.0:
        assert got == 0.0
    else:
        np.testing.assert_allclose(got, expected, rtol=1e-4)
