"""Whole-column Fortran <-> GT4Py consistency, over every scenario and both backends.

For each scenario the SAME column is pushed through the compiled Fortran
(``nwp_microphysics``: satad -> two_moment_mcrph -> satad) and through the GT4Py port,
and every prognostic field must agree. The reference is the real Fortran binary run at
test time -- not a committed CSV, and not a numpy transcription.

This replaces a test that compared against ``example/output_fields.csv`` at ``rtol=1e-6``.
Two things were wrong with that. The file was written at 9 significant digits, so it put a
~1e-9 floor under any comparison regardless of how good the port was; and 1e-6 was loose
enough to accept a genuine 5e-7 error in the depositional-growth coefficients, which is
how that bug survived. Both are fixed: the driver now writes 17 digits, and the tolerance
here is set from what the port actually achieves (see conftest.RTOL).

``example/output_fields.csv`` is still regenerated by ``make run`` and is still useful for
eyeballing a column by hand -- it is simply no longer what decides whether the port is
correct.
"""

from __future__ import annotations

import gt4py.next as gtx
import numpy as np
import pytest

from minimal_mcrph import particles as p
from minimal_mcrph.driver import ColumnState, Driver
from minimal_mcrph.tests.conftest import CHECKED_FIELDS, as_columns, compare_columns
from minimal_mcrph.tests.fortran_runner import run_fortran
from minimal_mcrph.tests.scenarios import SCENARIOS

_NAMES = sorted(SCENARIOS)
_BACKENDS = [None, gtx.gtfn_cpu]
_BACKEND_IDS = ["embedded", "gtfn_cpu"]

# ColumnState carries the fields the port evolves; the CSV additionally holds ssat,
# ninagi and qrsflux, which are inert in this configuration.
_STATE_FIELDS = tuple(
    f.name for f in ColumnState.__dataclass_fields__.values() if f.name != "hhl"
)


def _state(fields, hhl):
    return ColumnState(hhl=hhl, **{name: fields[name].copy() for name in _STATE_FIELDS})


@pytest.mark.parametrize("backend", _BACKENDS, ids=_BACKEND_IDS)
@pytest.mark.parametrize("name", _NAMES)
def test_full_column_matches_fortran(name, backend):
    fields, hhl, dt = SCENARIOS[name]

    reference = run_fortran(fields, hhl, dt=dt)
    result = Driver(backend=backend).run_timestep(_state(fields, hhl), dt=dt)

    compare_columns(name, as_columns(result), reference)


@pytest.mark.parametrize("name", _NAMES)
def test_physical_invariants(name):
    """Oracle-free checks on the port's own output.

    These hold for reasons independent of the Fortran, so they still say something if
    both implementations were wrong in the same way -- the one failure mode a pure
    consistency test cannot see.
    """
    fields, hhl, dt = SCENARIOS[name]
    result = Driver().run_timestep(_state(fields, hhl), dt=dt)
    out = as_columns(result)

    # Total water is conserved: this scheme has no sedimentation and no surface flux, so
    # every process only moves mass between the vapour and condensate categories.
    water = ("qv", "qc", "qr", "qi", "qs", "qg", "qh")
    before = sum(fields[f] for f in water)
    after = sum(out[f] for f in water)
    np.testing.assert_allclose(
        after, before, rtol=1e-12, atol=1e-18,
        err_msg=f"[{name}] total water not conserved across the timestep",
    )  # fmt: skip

    # Nothing goes negative.
    for field in CHECKED_FIELDS:
        assert np.all(out[field] >= 0.0), f"[{name}] {field} went negative"

    # Temperature stays physical -- a runaway latent-heat update would show up here well
    # before it produced a NaN.
    assert np.all(np.isfinite(out["tk"]))
    assert np.all(out["tk"] > 150.0) and np.all(out["tk"] < 350.0)

    # After the final size clips, mean particle mass is inside each species' bounds.
    for q_name, n_name, particle in (
        ("qc", "qnc", p.CLOUD), ("qr", "qnr", p.RAIN), ("qi", "qni", p.ICE),
        ("qs", "qns", p.SNOW), ("qg", "qng", p.GRAUPEL), ("qh", "qnh", p.HAIL),
    ):  # fmt: skip
        present = out[q_name] > 0.0
        if not present.any():
            continue
        x = out[q_name][present] / out[n_name][present]
        assert np.all(x >= particle.x_min * (1.0 - 1e-12)), f"[{name}] {q_name} below x_min"
        assert np.all(x <= particle.x_max * (1.0 + 1e-12)), f"[{name}] {q_name} above x_max"
